import json
import os

from xhtml2pdf import pisa

from db import get_db

DISCLAIMER = (
    "This report was generated by Rivela AI, an AI-based clinical decision support tool. "
    "It is intended to assist, not replace, clinical judgement. All findings must be "
    "reviewed and confirmed by a qualified healthcare professional before any diagnosis "
    "or treatment decision is made."
)


def get_prediction(prediction_id):
    conn = get_db()
    row = conn.execute(
        """SELECT predictions.*, users.username AS clinician_username,
                  patients.name AS patient_name, patients.dob AS patient_dob,
                  patients.sex AS patient_sex
           FROM predictions
           JOIN users ON users.id = predictions.user_id
           LEFT JOIN patients ON patients.id = predictions.patient_id
           WHERE predictions.id = ?""",
        (prediction_id,),
    ).fetchone()
    conn.close()
    if row is None:
        return None

    record = dict(row)
    record["symptoms"] = json.loads(record["symptoms_json"]) if record["symptoms_json"] else {}
    record["xray_probs"] = json.loads(record["xray_probs_json"]) if record["xray_probs_json"] else None
    record["symptom_probs"] = (
        json.loads(record["symptom_probs_json"]) if record["symptom_probs_json"] else None
    )
    record["fusion_result"] = (
        json.loads(record["fused_result_json"]) if record["fused_result_json"] else None
    )
    record["xray_uncertainty"] = (
        json.loads(record["xray_uncertainty_json"]) if record.get("xray_uncertainty_json") else None
    )
    record["symptom_uncertainty"] = (
        json.loads(record["symptom_uncertainty_json"]) if record.get("symptom_uncertainty_json") else None
    )
    return record


def get_checked_symptoms(record):
    return [name.replace("_", " ") for name, value in record["symptoms"].items() if value]


def build_imaging_narrative(record):
    if not record["xray_probs"]:
        return "No radiographic imaging data is available for this assessment."

    sorted_probs = sorted(record["xray_probs"].items(), key=lambda kv: kv[1], reverse=True)
    top_disease, top_prob = sorted_probs[0]

    # Confidence framing
    if top_prob >= 0.85:
        confidence_phrase = f"with high model confidence ({top_prob * 100:.1f}%)"
    elif top_prob >= 0.60:
        confidence_phrase = f"with moderate model confidence ({top_prob * 100:.1f}%)"
    else:
        confidence_phrase = f"at a relatively low confidence level ({top_prob * 100:.1f}%)"

    lines = [
        f"Posteroanterior chest radiograph analysis by the Rivela AI X-ray model identified "
        f"{top_disease} as the primary finding, {confidence_phrase}. "
    ]

    # Secondary findings above a meaningful threshold (>15%) excluding the top
    secondary = [(d, p) for d, p in sorted_probs[1:] if p >= 0.15]
    if secondary:
        sec_text = "; ".join(f"{d} ({p * 100:.1f}%)" for d, p in secondary[:3])
        lines.append(
            f"Additional findings of note include: {sec_text}. "
            "These secondary probabilities do not constitute independent diagnoses and "
            "should be interpreted alongside the primary finding and clinical context. "
        )

    # Uncertainty context
    xu = (record.get("xray_uncertainty") or {}).get(top_disease)
    if xu:
        lines.append(
            f"Monte Carlo uncertainty estimation across 25 stochastic inference passes "
            f"yielded a mean probability of {xu['mean'] * 100:.1f}% "
            f"(±{xu['std'] * 100:.1f}% standard deviation) for {top_disease}, "
            f"indicating {'low' if xu['std'] < 0.08 else 'moderate' if xu['std'] < 0.18 else 'high'} "
            f"epistemic uncertainty in this estimate. "
        )

    lines.append(
        "Grad-CAM saliency mapping was applied to localise the spatial regions "
        "that most influenced the model's output. "
        "The resulting activation overlay is available in the Analysis tab for visual verification "
        "of anatomical plausibility by the reviewing clinician."
    )

    return "".join(lines)


def build_symptom_narrative(record):
    checked_symptoms = get_checked_symptoms(record)

    if not record["symptom_probs"]:
        if not checked_symptoms:
            return "No symptom data was collected for this assessment."
        return (
            f"The patient reported the following symptoms: {', '.join(checked_symptoms)}. "
            "Symptom model analysis was not performed for this assessment."
        )

    sorted_probs = sorted(record["symptom_probs"].items(), key=lambda kv: kv[1], reverse=True)
    top_disease, top_prob = sorted_probs[0]

    if checked_symptoms:
        symptom_text = f"The patient reported the following symptoms: {', '.join(checked_symptoms)}."
    else:
        symptom_text = "No symptoms were recorded for this assessment."

    lines = [symptom_text + " "]
    lines.append(
        f"Symptom-based probabilistic analysis by the Rivela AI symptom model identified "
        f"{top_disease} as the most consistent diagnosis ({top_prob * 100:.1f}% probability). "
    )

    # Runner-up
    if len(sorted_probs) > 1:
        second_disease, second_prob = sorted_probs[1]
        if second_prob >= 0.10:
            lines.append(
                f"The differential consideration of {second_disease} was also noted "
                f"({second_prob * 100:.1f}%), though ranked below the primary finding. "
            )

    su = (record.get("symptom_uncertainty") or {}).get(top_disease)
    if su:
        lines.append(
            f"Model uncertainty for this symptom-based output was estimated at "
            f"±{su['std'] * 100:.1f}% across repeated stochastic passes. "
        )

    return "".join(lines)


def build_combined_narrative(record):
    fr = record.get("fusion_result")

    if not fr:
        top = record.get("top_disease", "unknown")
        return (
            f"This assessment was conducted using a single diagnostic modality. "
            f"The top finding was {top}. "
            "Multimodal fusion, which combines X-ray and symptom evidence using "
            "disease-specific weighting, was not performed as only one source of "
            "data was available. Clinical interpretation should account for the "
            "absence of corroborating evidence from the alternate modality."
        )

    top = fr["top_disease"]
    score = fr["top_score"] * 100
    status = fr["status"]

    status_descriptions = {
        "confirmed":  f"a fused confidence score of {score:.1f}%, surpassing the confirmation threshold of 70%. This classification indicates strong concordant evidence across both modalities.",
        "possible":   f"a fused confidence score of {score:.1f}%, meeting the threshold for a possible finding (45–70%). The diagnosis is plausible but should be interpreted with caution and corroborated with further clinical investigation.",
        "uncertain":  f"a fused confidence score of {score:.1f}%, which falls below the threshold for a definitive or probable classification. The finding is indeterminate; further investigation is recommended before clinical action is taken.",
    }

    lines = [
        f"Multimodal fusion combining radiographic and symptom-based evidence identified "
        f"{top} as the leading diagnosis, with "
        f"{status_descriptions.get(status, f'a confidence score of {score:.1f}%')} "
    ]

    if fr.get("conflict"):
        lines.append(
            f"A modality conflict was detected: the X-ray model independently favoured "
            f"{fr['xray_top']}, while the symptom model independently favoured "
            f"{fr['symptom_top']}. The fusion algorithm has weighted these outputs according "
            f"to disease-specific reliability weights from the fusion configuration; however, "
            "the disagreement between modalities warrants closer clinical scrutiny of this case."
        )
    else:
        lines.append(
            f"Both the X-ray and symptom models were in agreement, each independently "
            f"identifying {top} as their top finding, which strengthens the overall assessment."
        )

    return " ".join(lines)


def build_narrative(record):
    """Backward-compatible single-string narrative used by PDF and plain-text contexts."""
    parts = [
        build_imaging_narrative(record),
        build_symptom_narrative(record),
        build_combined_narrative(record),
    ]
    return " ".join(p.strip() for p in parts if p.strip())


def get_all_predictions_for_patient(patient_id):
    conn = get_db()
    rows = conn.execute(
        """SELECT predictions.*, users.username AS clinician_username,
                  patients.name AS patient_name, patients.dob AS patient_dob,
                  patients.sex AS patient_sex
           FROM predictions
           JOIN users ON users.id = predictions.user_id
           LEFT JOIN patients ON patients.id = predictions.patient_id
           WHERE predictions.patient_id = ?
           ORDER BY predictions.created_at ASC""",
        (patient_id,),
    ).fetchall()
    conn.close()
    records = []
    for row in rows:
        r = dict(row)
        r["symptoms"] = json.loads(r["symptoms_json"]) if r["symptoms_json"] else {}
        r["xray_probs"] = json.loads(r["xray_probs_json"]) if r["xray_probs_json"] else None
        r["symptom_probs"] = json.loads(r["symptom_probs_json"]) if r["symptom_probs_json"] else None
        r["fusion_result"] = json.loads(r["fused_result_json"]) if r["fused_result_json"] else None
        r["xray_uncertainty"] = json.loads(r["xray_uncertainty_json"]) if r.get("xray_uncertainty_json") else None
        r["symptom_uncertainty"] = json.loads(r["symptom_uncertainty_json"]) if r.get("symptom_uncertainty_json") else None
        records.append(r)
    return records


def make_link_callback(static_folder):
    def link_callback(uri, rel):
        if uri.startswith("/static/"):
            return os.path.join(static_folder, uri[len("/static/"):])
        return uri
    return link_callback


def render_pdf(html_string, static_folder):
    import io

    output = io.BytesIO()
    result = pisa.CreatePDF(
        html_string, dest=output, link_callback=make_link_callback(static_folder)
    )
    if result.err:
        raise RuntimeError("Failed to generate PDF report")
    return output.getvalue()
